# Generated by Django 3.2.5 on 2021-07-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to='images/')),
                ('bio', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_caption', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('comments', models.TextField(max_length=100)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('profile', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='insta.profile')),
            ],
        ),
    ]
